# Generated by Django 4.2 on 2023-04-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_employee', '0004_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
