# Generated by Django 4.2 on 2023-04-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_employee', '0007_rename_department_employee_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department_name',
            new_name='department',
        ),
    ]
