# Generated by Django 4.2 on 2023-04-14 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_employee', '0010_alter_employee_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('counterparty', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('projects_participate', models.ManyToManyField(related_name='participate_by', to='core_employee.employee')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_employee.employee')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
        ),
    ]
