# Generated by Django 4.2 on 2023-04-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_employee', '0010_alter_employee_title'),
        ('core_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projects_participate',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='members_by', to='core_employee.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
