# Generated by Django 4.2 on 2023-04-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_project', '0004_alter_timeentry_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start_time',
            field=models.DateField(),
        ),
    ]
