# Generated by Django 4.2 on 2023-07-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_task', '0003_alter_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Закончено'), ('deleted', 'Удалено')], default='new', max_length=20),
        ),
    ]
